version: "3"
services:
  kafka:
    image: 'bitnami/kafka:3.4.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
networks:
  #自定义网络
  kafka: 
    driver: custom-driver-1
  #使用已经存在的网络
  default:
    external: 
      name: apps
