version: "3.8"

services:
  redis-master:
    image: redis:7.2
    container_name: redis-master
    command: redis-server --requirepass 123456  --masterauth 123456
    ports:
      - 6379:6379
    volumes:
      - $PWD/Docker_Data/redis/master/data:/data

  redis-slave1:
    image: redis:7.2
    container_name: redis-slave-1
    ports:
      - 6381:6379
    command:  redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
    volumes:
      - $PWD/Docker_Data/redis/slave1/data:/data

  redis-slave2:
    image: redis:7.2
    container_name: redis-slave-2
    ports:
      - 6380:6379
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
    volumes:
      - $PWD/Docker_Data/redis/slave2/data:/data

  sentinel1:
    image: redis:7.2
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel/sentinel1.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis:7.2
    container_name: redis-sentinel-2
    ports:
    - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel/sentinel2.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis:7.2
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel/sentinel3.conf:/usr/local/etc/redis/sentinel.conf

    
networks:
  default:
    name: reids-net
    driver: bridge
  apps: #使用已经存在的网络
      external: true